name-template: 'v$RESOLVED_VERSION 🛠'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: 'Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'Updates and Patches'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'patch'
      - 'fixes'
      - 'update'
  - title: 'CI/CD'
    labels:
      - 'ci'
      - 'cd'
  - title: ' Development'
    label: 'dev'
  - title: 'Documentation'
    label: 'docs'

change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES
  
autolabeler:
  - label: 'documentation'
    files:
      - '*.mdx'
  - label: 'docs'
    files:
      - '*.md'
    branch:
      - '/docs{0,1}\/.+/'
