---
topic: Trade and Settlement
---

# Trade and Settlement

## 401. Submission of Trades

(A). Upon matching of a trade effected on or pursuant to the rules of the
Exchange, the Exchange shall promptly submit to Commodity Stream, LLC a trade
report generated by the electronic trading system of the Exchange. The report
shall show for each trade

    (i) the identity of each Clearing Participant and/or Network Participant,
    (ii) whether bought or sold,
    (iii) quantity,
    (iv) delivery month,
    (v) the price,
    (vi) whether for house, Customer, or non- Customer account, and
    (vii) such other information as may be required by Commodity Stream, LLC.

(B). If Commodity Stream, LLC determines that any trade report submitted
pursuant to this Rule 401 contains a material error or is otherwise not eligible
for clearing by Commodity Stream, LLC, Commodity Stream, LLC may reject such
trade and notify the Exchange of such rejection, setting forth the basis of such
objection.

## 402\. Clearance and Substitution

(a) The submission of a Contract (Smart Contract or a Normal Contract) to
Commodity Stream, LLC by or on behalf of the buying and selling Clearing
Participants shall constitute a request, by such Clearing Participants, for the
clearing of such Contract by Commodity Stream, LLC. Upon the acceptance thereof
by Commodity Stream, LLC, which ordinarily shall be deemed to occur upon the
receipt of matched trade data from the Exchange, the Contract shall be novated
and Commodity Stream, LLC shall be substituted as, and assume the position of,
seller to the Clearing Participant buying such Contract and buyer from the
Clearing Participant selling such Contract. Upon such substitution, such buying
and selling Clearing Participants shall be released from their obligations to
each other, and Commodity Stream, LLC shall be deemed to have succeeded to all
the rights, and to have assumed all the Obligations, of the Clearing
Participants that were party to such Contract, in each case as provided in the
Rules.

(b) Where an Commodity Stream, LLC Clearing Participant and/or Network
Participant acts to clear a Contract made for the account of a Customer, the
Commodity Stream, LLC Clearing Participant becomes obligated to Commodity
Stream, LLC, and Commodity Stream, LLC becomes obligated to the Commodity
Stream, LLC Clearing Participant, with respect to such Contract in the same
manner and to the same extent as if the Contract were for the account of the
Commodity Stream, LLC Clearing Participant.

(c) Notwithstanding the provisions of paragraph (a), a trade shall not be
accepted for clearing, and Commodity Stream, LLC shall not be substituted for a
given Contract, unless the Margin for such Contract is made available to
Commodity Stream, LLC, by or for both Clearing Participants, pursuant to
Rule 403.

## 403\. Margin

(a) Each Network and Clearing Participant SHALL deposit funds or Collateral in
the form of the applicable quantity of the deliverable underlying commodity
and/or deliverable asset required to fully collateralize orders pursuant to the
contract specifications contained in the Rulebook, including payment of
premiums, payment in exchange for delivery or to fulfill delivery obligations,
as applicable, prior to submission of such orders to the Exchange. Fund and
Collateral transfers made by a Clearing Participant to the Clearinghouse or by
the Clearinghouse to a Clearing Participant are irrevocable and unconditional
when effected. The Clearing Participant shall be responsible for all fees
associated with wires or transfers of Collateral to the Clearinghouse.

(b) Subject to the terms and conditions of the Clearinghouse, Clearing
Participants may deposit the following as Margin:

    (1) cash;

    (2) the underlying commodity; and

    (3) any other form of Collateral deemed acceptable by the Risk Management Committee upon the Risk Management Committee’s approval of such Collateral as communicated through Clearinghouse notices. The Clearinghouse will value margin Collateral as it deems appropriate.

(c) Funds and Collateral must be and remain unencumbered. Except as otherwise
provided herein, each Clearing Participant posting funds or Collateral hereby
grants to the Clearinghouse a first priority security interest in and
unencumbered lien against any Margin, Contracts, positions and other funds,
property and any other Collateral deposited with the Clearinghouse by the
Clearing Participant, including without limitation such Clearing Participant’s
Member Property Accounts, the Customer Accounts of such Clearing Participant’s
Customers, and all securities entitlements held therein. A Clearing Participant
shall execute any documents required by Commodity Stream, LLC to create, perfect
and enforce such lien. Each Clearing Participant hereby agrees that with respect
to any funds or Collateral which is or may be credited to the Clearing
Participant’s Member Property Account or Customer Account, as applicable, the
Clearinghouse shall have control pursuant to Section 9-106(a) and 8-106(e) of
the UCC and a perfected security interest pursuant to Section 9-314(a) of the
UCC.

(d) Commodity Stream, LLC may assign, pledge, repledge or otherwise create a
lien on or security interest in, and enter into repurchase agreements involving,
Margin, Contracts, positions and other funds, property and any other Collateral
deposited with the Clearinghouse by the Clearing Participant, as permitted by
CFTC Regulations, held in or for such Clearing Participant’s Member Property
Accounts or the Customer Accounts of such Clearing Participant’s Customers to
secure the repayment of funds that may be borrowed by Commodity Stream, LLC.

(e) Clearing Participant must transfer the funds and Collateral to the
Clearinghouse which will hold funds and Collateral on behalf of the Clearing
Participant. Commodity Stream, LLC will credit to the Clearing Participant the
funds and Collateral that such Clearing Participant deposits. Funds and
Collateral shall be held by the Clearinghouse until a Clearing Participant
submits a withdrawal notification, unless otherwise stipulated by these Rules.
Commodity Stream, LLC will not be responsible for any diminution in value of
funds or Collateral that a Clearing Participant deposits with the Clearinghouse,
except, in the case of cash, the diminution of value is as a direct result of
investment activity of the Clearinghouse, such activity having been conducted in
full compliance with CFTC Regulations. Any fluctuation in markets is the risk of
each Clearing Participant. Any interest earned on Clearing Participant funds or
Collateral may be retained by the Clearinghouse.

(f) If a Clearing Participant is in Default, Commodity Stream, LLC may foreclose
on and sell any of the Margin deposited by such Clearing Participant without
notice.

(g) Commodity Stream, LLC shall be empowered to invest and reinvest all or part
of the funds constituting Margin. Such investments shall be for the account and
risk of Commodity Stream, LLC, and any income and gains on such investments and
interest on such deposits shall belong to Commodity Stream, LLC and may be
withdrawn from the account holding the Margin and deposited with the general
funds of Commodity Stream, LLC.

## 404\. Offset and Settlement

(a) Where, as the result of novation under Rule 402, a Clearing Participant has
bought and sold a Contract on or subject to the Rules of the Exchange with the
same expiration, or otherwise deemed equivalent by the Clearinghouse, the
purchase and sale will be offset by Commodity Stream, LLC through the timely
submission of instructions by the Clearing Participant containing such
information as Commodity Stream, LLC may require in accordance with its
procedures. A Clearing Participant shall be required to pay the loss or entitled
to collect the profit, as the case may be, upon such offsetting transactions,
and shall have no further rights or be under any further obligation with respect
thereto. For purposes of this Rule 404, the first Contracts made shall be deemed
the first Contracts offset.

(b) Contracts made and designated by the Network or Clearing Participant as for
the Network and/or Clearing Participant’s Customer Account shall not be offset
under this Rule 405 against Contracts designated by the Clearing Participant as
for the Clearing Participant’s own Member Property Account.

## 405\. Approved Depository Institutions

A bank, trust company or other depository that meets such financial and other
requirements of Commodity Stream, LLC may be designated by Commodity Stream, LLC
as an Approved Depository Institution.

## 406\. Statement of Trades and Contracts

Commodity Stream, LLC shall in the manner and at the time that it determines
from time to time make available to a Clearing Participant an accounting of
trades and Contracts for each Business Day on which such Clearing Participant
has trades to be cleared or Contracts open with Commodity Stream, LLC. Any
amounts the Clearing Participant has posted to Commodity Stream, LLC under Rule
403 shall be indicated on this statement

## 409\. Settlement Prices

As used in the Rules, the term “Settlement Price” means the settlement price for
a Contract for which positions remain open, as determined, intra-day and at the
close of regular trading hours, by the Exchange in accordance with its rules,
except in the case of manifest error or where Commodity Stream, LLC believes
that such settlement price does not reasonably reflect the value or price of the
Contract, in which case Commodity Stream, LLC, using its best efforts to consult
with the Exchange, shall determine the official Settlement Price; provided, that
Commodity Stream, LLC shall in such circumstances promptly notify the Exchange
and Clearing Participants, and the reasons for that determination and the basis
for the Settlement Price determined by Commodity Stream, LLC shall be published
in a notice to the Exchange and Clearing Participants.

## 410\. Delivery

After trading ceases for a Smart Contract and/or Normal Contract that is
physically settled, the Clearinghouse shall transfer the underlying to the
Account of the Clearing Participant that is required to accept delivery, from
the Account of the Clearing Participant obligated to make delivery, such full
collateralization having been transferred to the Clearinghouse’s custody at the
inception of the trade. Deliveries will occur on the Clearinghouse’s books and
records unless otherwise specified in the Exchange contract specifications.

## 411\. Reporting

Network and Clearing Participants shall make such reports in respect of trades,
Smart Contracts, Normal Contracts settlements and deliveries as may be as
prescribed by Commodity Stream, LLC.

copyright (c) 2021 Commodity Stream, LLC - All Rights Reserved CC-BY-NC-ND-2.5
